### ISSUE TITLE
Trouble getting cloudwatch data source to work with grafana/grafana:master container

### ISSUE THREAD

**Issue by a-panickar** [grafana/grafana-docker#164]
Hi,

I am having trouble configuring the cloudwatch dashboard when I am running the grafana container on my local machine. I am using the pre-built 'grafana/grafana:master' container published on docker hub an hour ago so I think I am using the latest bits.

I am running the container locally on my mac where I have generated the AWS creds and validated it by firing CLI commands and I am able to list metrics out of cloudwatch with the same creds. I then ran the docker container using the below command with the validated credentials ($AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY):

`	docker run \ `
`	-d \ `
`	-p 3000:3000 \ `
`	-e "GF_AWS_PROFILES=default" \ `
`	-e "GF_AWS_default_ACCESS_KEY_ID=<keyid>" \ `
`	-e  "GF_AWS_default_SECRET_ACCESS_KEY=<key>" \`
`	-e "GF_AWS_default_REGION=us-east-1" \`
`	grafana/grafana:master`

Shelling into the running container, I can see that the credentials file got created inside '/usr/share/grafana/.aws' directory with the environment variables I supplied. I did notice that the 'aws_session_token'/'aws_security_token' values which are normally present in the aws credentials file are missing here.

However, when I go to configure the cloudwatch data source I get a red box with a white caution sign and no other messages. I have selected 'credential file' as the auth provider and didn't provide any values for 'Credentials profile name' and 'Custom Metrics' fields and selected 'us-east-1' for 'Default Region' field.

I tried to check if I can get the data source to work with 'Access and Secret key' as the auth provider and providing the same AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and I still get the same red box, so looks like a problem getting the credentials to work from within the container.

I can't see any logs in the '/var/log/grafana/' directory so not sure why/where it's failing.

Any ideas on what I am doing wrong and how to troubleshoot this further?

 Thanks

**Comment by xlson** [comment]
Hi,

We had a bug in Grafana 5.1.0 that meant that the credentials file wouldn't be used (see #158). It has been fixed in 5.1.3 and should also be fixed in master. Try updating your master image by running `docker pull grafana/grafana:master` to make sure you have the latest version.

When setting up the datasource for CloudWatch, make sure that you have selected a region, it will not work otherwise.

**Comment by xlson** [comment]
I'm closing this issue as the bug should be fixed. Please let me know if that is not the case for you.

**Comment by a-panickar** [comment]
@xlson Sorry for the delayed response.

I tried again with the latest grafana master image from docker hub and I still see the issue.

Can you please help me answer the following questions?

1. Where are the logs being saved in the container?
2. Does grafana work with federated identities? The AWS keys I have generated are not from an IAM user instead of my federated identity attached to an IAM Role using STS. Is this a supported model? I have validated that the temp creds are working as expected before passing them to the container.
3. When I try to explicitly specify the generated credentials using the 'Access and Secret key' auth provider it still doesn't work so I suspect the credentials required are long-running IAM user credentials and not the STS generated temp credentials.

Thanks

**Comment by xlson** [comment]
@a-panickar no worries. 

It definitely sounds like

**Comment by a-panickar** [comment]
Thanks @xlson 

For using the temp credentials generated using STS with the AWS API's the session token must be included with the request so that AWS can verify that the temporary security credentials are valid.

Please find more info in the below link:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html

**Comment by a-panickar** [comment]
@xlson 

I was able to spend some time looking into the code today and I was able to tweak the code to make it work with the STS temp credentials. I passed in the session token as an environment variable (similar to ACCESS_KEY_ID and SECRET_ACCESS_KEY) and wrote the same to the aws credentials file by updating the run.sh file, rebuilt the container and it worked just fine.

**Comment by xlson** [comment]
@a-panickar Great. Can I see your modifications somewhere?

**Comment by a-panickar** [comment]
@xlson 

Pls find the updated code block below from run.sh file.

I updated the for loop block which writes out the passed-in environment variables to the aws credentials file to also write out the session token value if available. For the variable name I have followed the convention of GF_AWS_${profile}_SESSION_TOKEN which I hope is fine? Also, I am writing the same value to both 'aws_session_token' as well as 'aws_security_token' for backward compatibility reasons.

```bash
    for profile in ${GF_AWS_PROFILES}; do
        access_key_varname="GF_AWS_${profile}_ACCESS_KEY_ID"
        secret_key_varname="GF_AWS_${profile}_SECRET_ACCESS_KEY"
        session_token_varname="GF_AWS_${profile}_SESSION_TOKEN"
        region_varname="GF_AWS_${profile}_REGION"

        if [ ! -z "${!access_key_varname}" -a ! -z "${!secret_key_varname}" ]; then
            echo "[${profile}]" >> "$GF_PATHS_HOME/.aws/credentials"
            echo "aws_access_key_id = ${!access_key_varname}" >> "$GF_PATHS_HOME/.aws/credentials"
            echo "aws_secret_access_key = ${!secret_key_varname}" >> "$GF_PATHS_HOME/.aws/credentials"

            if [ ! -z "${!session_token_varname}" ]; then
                echo "aws_session_token = ${!session_token_varname}" >> "$GF_PATHS_HOME/.aws/credentials"
                echo "aws_security_token = ${!session_token_varname}" >> "$GF_PATHS_HOME/.aws/credentials"
            fi
            
            if [ ! -z "${!region_varname}" ]; then
                echo "region = ${!region_varname}" >> "$GF_PATHS_HOME/.aws/credentials"
            fi
        fi
    done

```

**Comment by xlson** [comment]
Thanks for figuring out how to solve this and sorry for taking so long to get back to you.

I'm curious, what is your use case for supporting STS credentials with Grafana? Are you continously updating the container with new credentials? From what I read the STS credentials only last 36 hours at most. Code wise it looks fine and we should probably add this to the run script.

**Comment by a-panickar** [comment]
@xlson No worries...

Since mine was a local use-case the token expiration period is sufficiently long that I won't need to worry about it. In my workflow the creds get generated in the beginning, the tests are run, the grafana container is launched, dashboards imported and data analyzed at the end of the test run.

**Comment by xlson** [comment]
grafana-docker has been moved into the main repository and this functionality exists as a PR here: https://github.com/grafana/grafana/pull/12887
